# Generated by Django 2.0.5 on 2018-05-24 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CMDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.GenericIPAddressField(verbose_name='主机地址')),
                ('port', models.CharField(max_length=10, verbose_name='主机端口')),
                ('team', models.CharField(choices=[('0', '运维组'), ('1', '测试组'), ('2', '网络组'), ('3', '软件组')], max_length=50, verbose_name='使用部门')),
                ('func', models.CharField(max_length=50, verbose_name='机器用途')),
                ('config', models.CharField(max_length=50, verbose_name='硬件配置')),
                ('operation', models.CharField(max_length=30, verbose_name='运维人员')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
    ]
